# Generated by Django 5.2.14 on 2026-05-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imageapp", "0002_imagedata_prediction_alter_imagedata_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagedata",
            name="probability",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
